### ISSUE TITLE
Version 0.4.6 Todo

### ISSUE THREAD

**Issue by kilbot** [kilbot/WooCommerce-POS#114]
- [ ] Changing the email address in the support form does not change the ‘reply-to’ address.
- [ ] Some gateways display symbols as the credit card placeholder, eg: â€¢â€¢â€¢â€¢ â€¢â€¢â€¢â€¢ â€¢â€¢â€¢â€¢ â€¢â€¢â€¢â€¢, also special characters are displayed incorrectly, eg: Devolución
- [ ] Unique email address should be removed as a hard dependence, eg: for stores that create user accounts without email addresses.
- [ ] Cart inputs need to filter for html, eg: when copy&pasting
- [ ] Some Pro users are still experiencing problems with POS totals not showing in reports
- [ ] IE Edge is compatible with WooCommerce POS, the warning notice needs to be removed
- [ ] POS should pass URL query params to the API requests, eg: ?lang=pl
- [ ] Address formats should change based on locale.
- [ ] WP Admin order list should contain more information, eg: cashier, store.
- [ ] A conflict has been reported with Relevanssi which affects product search.
- [ ] Cash and Card options not appearing in edit order billing details for some users.
- [ ] Regression: The default receipt template for Pro users has stopped working.
- [ ] Plugin conflict prevents Checkout settings showing for some users.
- [ ] WooCommerce POS will give a Indexed DB error [object event] if Private Browsing is enabled.
- [ ] Regression: Thousand separator is being treated as decimal point on number pad.
- [ ] WooCommerce POS is not compatible with NextGEN Gallery.
- [ ] A conflict has been reported with Subscripto, this causes a fatal error for Pro users.
- [ ] Warning notifications not showing if minimum requirements not met.
- [ ] Printing issues using Firefox.
- [ ]  ePOS Print & Google CloudPrint options
- [ ] Ability to open orders
 - [ ] requires Backbone relations
- [ ] Ability to edit order properties after checkout

**Comment by kilbot** [comment]
![screen shot 2016-01-17 at 2 09 26 pm](https://cloud.githubusercontent.com/assets/639807/12617831/5358ba3c-c54c-11e5-8ae3-336436cda0cb.png)

Total miscalculation in example above.

**Comment by kilbot** [comment]
![screen shot 2016-01-27 at 11 20 35 pm](https://cloud.githubusercontent.com/assets/639807/12617910/9e876152-c54c-11e5-8dd2-1d8835593241.png)

Total miscalculation on example above.

**Comment by kilbot** [comment]
![screen shot 2016-02-03 at 11 59 40 pm](https://cloud.githubusercontent.com/assets/639807/12788370/2b724190-cad4-11e5-9240-87730d3577a2.png)

Use of 'Any ...' option for variations is not handled correctly by the POS.

**Comment by kilbot** [comment]
![img_20160205_135420](https://cloud.githubusercontent.com/assets/639807/12863986/648b8058-ccba-11e5-8703-1726b4b8f0fa.jpg)

Rounding error above.

**Comment by kilbot** [comment]
![screen shot 2016-05-08 at 4 19 15 pm](https://cloud.githubusercontent.com/assets/639807/15096727/b7ec62fa-1538-11e6-9517-5bda079fa812.png)
