### ISSUE TITLE
TODO list for 0.4.0-beta

### ISSUE THREAD

**Issue by kilbot** [kilbot/WooCommerce-POS#60]
The following items are things I am working on at this minute. Please check back to this list if you want a progress update.

- [x] Payment processing, order status
- [x] Receipt template
- [x] Remove completed orders
- [x] Barcode search
- [x] Improvements to product download
- [x] Tab titles
- [x] Numpad discount (& other bugs)
- [x] Support emails

Note: the above list includes items for the free plugin only. A similar list is being tracked for the Pro plugin.

**Comment by timit13** [comment]
Hi Paul

Where can I see the list for the Pro plugin?
By when can we expect version 0.4?

Thanks!
serge

**Comment by timit13** [comment]
Hi Paul

Any news regarding version 0.4?

Thanks for the update!

Serge

**Comment by kilbot** [comment]
Version 0.4-beta is [available for download from WordPress.org](https://downloads.wordpress.org/plugin/woocommerce-pos.zip) and the Pro beta is available for download from your [account page](https://woopos.com.au/my-account/).

I will be writing a full blog post and send out an email to all Pro users with more details tomorrow, but wanted to give you the links as soon as possible.

**Comment by EgbertJan** [comment]
Hi Paul,

I did a deinstall and install of both packages and configure settings
gives me a error message:

There has been an error loading the settings, please contact support
<mailto:support@woopos.com.au>

De-activating PRO does not make any difference Trying to run (view POS)
give me a blank screen.

EgbertJan

PS I will head over to the tranlation site asap; I guess there is a lot
of work to be done...



Paul Kilmurray schreef op 23-5-2015 om 20:07:

**Comment by kilbot** [comment]
Ah .. looks like I missed a file during the subversion commit at WordPress.org. If you redownload and install you should get a better result. I've also updated the [translations repo](https://github.com/kilbot/WooCommerce-POS-Language-Packs).

Thanks!

**Comment by EgbertJan** [comment]
It is fine now. POS generally looks very nice. Amounts are correct (at a
first glance). Access to products/users/orders is really neat.

Observation: the entry of a barcode adds the product to the bill but the
barcode is not ereased but a second scan is concatenated to the previous
barcode. I seem to remeber that repeated scanning did work in 0.3.5.

I'm used to login as admin first and then go to "view POS" but is there
no way back to normal admin view?

The DB seems much faster that it used to be. There is no erease and
reload anymore in the footer of the left window; is it not needed anymore?

I'll have to fiddle a bit with the printed output template to get a
readable receipt. I do not have the receipt printer (TSP-100) at hand at
the moment, though. That has to wait a while.

All in all 0.4beta is huge improvement.
CU
Egbert Jan

Paul Kilmurray schreef op 24-5-2015 om 2:58:

**Comment by kilbot** [comment]
> I'm used to login as admin first and then go to "view POS" but is there no way back to normal admin view?

You mean a link in the menu back to the WordPress admin? Good point, I will add that before release.

> There is no erease and reload anymore in the footer of the left window; is it not needed anymore?

The POS no longer downloads every product on install. As you search for products or scroll pages it will download them as needed and store them locally. You can clear the local storage on the support page if the data becomes out-of-sync for some reason.
