### ISSUE TITLE
0.4 Todo

### ISSUE THREAD

**Issue by kilbot** [kilbot/WooCommerce-POS#75]
The following is my todo list based on feedback and bug reports from 0.4-beta.
- [x] product variation bug for long variation names & names with brackets
- [x] barcode should be cleared after successful add to cart
- [x] existing customer address is not populated with POS order
- [x] bug selecting user in admin settings
- [x] PRO - bug selecting new cart immediately after selecting new cart
- [x] PRO - update db
- [x] PRO - reports

Additional tasks before release:
- [x] email translators
- [x] email Pro users
- [ ] update documentaion/website

If you have anything to add, leave a comment. Please try and keep it to bug reports - this is not the place for feature requests or how-to guides.

**Comment by timit13** [comment]
product variation bug for long variation names & names with brackets... AND also with "umlauts" like ä, ö, ü.
